### ISSUE TITLE
Script does not recognize some commands?

### ISSUE THREAD

**Issue by Deses** [nisay759/arpscan#1]
Hello! I just found this and I was giving it a go...

```
pi@raspberrypi:~/git $ sudo ./arpscan.sh enxb827eb80eb26
./arpscan.sh: linea 35: grep: command not found
./arpscan.sh: linea 35: ip: command not found
```

Looks like there's something iffy in that line!

The command by itself works ok:

```
pi@raspberrypi:~/git $ ip a show dev enxb827eb80eb26 | grep -Eo 'inet .* brd' | cut -f2 -d' '
192.168.1.32/24
```

And this is also working 🤔 
```
pi@raspberrypi:~/git $ ip=$(ip a show dev enxb827eb80eb26 | grep -Eo 'inet .* brd' | cut -f2 -d' ')
pi@raspberrypi:~/git $ echo $ip
192.168.1.32/24
```

**Comment by nisay759** [comment]
Hi,
It does seem strange indeed, and I suspect it might be related to your environment.
Can you launch the script in debug mode and post the output ?
`sudo bash -x arpscan.sh enxb827eb80eb26`
Also, the following 2 commands:
`whereis grep`
`whereis ip`

**Comment by Deses** [comment]
Hello!
Here's the output:
```
pi@raspberrypi:~/git $ sudo bash -x arpscan.sh enxb827eb80eb26
+ export PATH=/usr/bin
+ PATH=/usr/bin
+ [[ 0 -ne 0 ]]
+ '[' 1 -ne 1 ']'
+ dev=enxb827eb80eb26
++ ip a show dev enxb827eb80eb26
++ grep -Eo 'inet .* brd'
arpscan.sh: line 35: ip: command not found
arpscan.sh: line 35: grep: command not found
++ cut -f2 '-d '
+ hostIP=
+ [[ -z '' ]]
+ exit 1


pi@raspberrypi:~/git $ whereis grep
grep: /bin/grep /usr/share/man/man1/grep.1.gz /usr/share/info/grep.info.gz


pi@raspberrypi:~/git $ whereis ip
ip: /bin/ip /sbin/ip /usr/share/man/man8/ip.8.gz /usr/share/man/man7/ip.7.gz

```

**Comment by nisay759** [comment]
Okay, so the problem seems that the script exports the `PATH` variable to only contain `/usr/bin`, whereas in raspbian the `ip` and `grep` binaries reside in `/bin`.
I pushed a commit to add `/bin` and `/sbin` as well.
Can you pull and see if it works ?

**Comment by Deses** [comment]
That worked pretty well! I had to `apt install arping` and it started fussing about arping - command not found.

```
pi@raspberrypi:~/git $ whereis arping
arping: /usr/sbin/arping /usr/share/man/man8/arping.8.gz
```

I added `/usr/sbin` to the PATH variable and now it it finally not throwing errors. :)
`export PATH="/usr/bin:/bin:/sbin:/usr/sbin"`
But it's also not outputting anything!

I didn't see anthing wrong after running `sudo bash -x arpscan.sh enxb827eb80eb26`.
https://gist.github.com/Deses/8c5e8d1c8a0b1b97db0d8defcceecc33

**Comment by nisay759** [comment]
If it does not output, then maybe no hosts are discoverable on your network.
Do you see any hosts when running `ip neigh show` ?

**Comment by Deses** [comment]
`ip neigh show` shows many hosts, both existing ones and IPs that never had any device using it. I prefer `sudo arp-scan --interface=enxb827eb80eb26 --localnet -g`:

```
Interface: enxb827eb80eb26, datalink type: EN10MB (Ethernet)
Starting arp-scan 1.9 with 256 hosts (http://www.nta-monitor.com/tools/arp-scan/)
192.168.1.1     
192.168.1.2    
192.168.1.3     
192.168.1.33  
192.168.1.63  
192.168.1.90
192.168.1.64    

8 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.9: 256 hosts scanned in 7.927 seconds (32.29 hosts/sec). 7 responded
```

**Comment by Deses** [comment]
This isn't fixed, the script still isn't outputting anything, I don't understand why you closed the issue....
